In [12]:
# array List
a = [1,2]
print("Array List ",a,"and its type", type(a))

# Array list Multiplication - Repeats
print("Repeats ",2*a)

# Array List Addition - Concatenates
b = [3,4]
print("Concatenation",a+b)

Array List  [1, 2] and its type <class 'list'>
Repeats  [1, 2, 1, 2]
Concatenation [1, 2, 3, 4]


In [43]:
# Numpy array and its Operation

import numpy as np
a = np.array([1,2])
print("Numpy Array ",a,"and its type", type(a))
print("Multiplication with constant", a*2)
print("Addition with constant", 2+a)
b= np.array([3,4])
print("Addition with other Numpy Array", a+b)
print("Mulplication with Other Array", a*b) # here * mean component wise or else Voilation of Matrix multiplication
c = np.matmul(b,a)
print(c)

# We can also create numpy array using array list
c= [[1,2,3], [4,5,6]]
x= np.array(c)
print(x , x.ndim)

Numpy Array  [1 2] and its type <class 'numpy.ndarray'>
Multiplication with constant [2 4]
Addition with constant [3 4]
Addition with other Numpy Array [4 6]
Mulplication with Other Array [3 8]
11
[[1 2 3]
 [4 5 6]] 2


In [95]:
# Numpy array can also be created using
# numpy.arange(start, stop, step, dtype=None)
a = np.arange(5,10,2)
print(a)

randomArray = np.random.random((4,4))
print(randomArray)

# we can specify random range

randomRange= np.random.randint(1,10, (5,3)) # start, stop , (rows, columns)
print(randomRange)


# reshaping Numpy array 

print("**********************************************")
reshapingArray = np.arange(0,20).reshape((5,4))
print(reshapingArray)
print(reshapingArray[2,3])
print(reshapingArray[3,3])
print(reshapingArray[0:3,0:4]) # 3 and 4 exclusive

[5 7 9]
[[0.32279689 0.97700536 0.9773375  0.38644001]
 [0.51537981 0.33648684 0.33151784 0.92506396]
 [0.2227223  0.46674991 0.01924061 0.28979872]
 [0.93527931 0.15658743 0.1458239  0.29840541]]
[[3 6 4]
 [6 5 3]
 [3 6 1]
 [1 8 2]
 [5 5 6]]
**********************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
11
15
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [102]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([7,8,9])
print(A.shape,B.shape)
c= np.dot(A,B)
print(c)




(2, 3) (3,)
[ 50 122]
