## Linear Algebra

In [ ]:
import numpy as np

#### Using numpy.matrix

In [28]:


# solving Matrices using numpy 
# 3x + 6y - 5z= 12
# x − 3y + 2z = −2
# 5x − y + 4z = 10
# Ax = B
# Solving x = A(inverse) B
a = np.matrix([
    [3, 6, -5],
    [1, -3, 2],
    [5, -1, 4]
])

b= np.matrix([
    [12],
    [-2],
    [10]
])
print(a.shape,type(a), b.shape,type(b))

(3, 3) <class 'numpy.matrixlib.defmatrix.matrix'> (3, 1) <class 'numpy.matrixlib.defmatrix.matrix'>


In [23]:
ans = a ** (-1) * b
print(a)
print(b)
print(ans)
print("****** Verifying Answer as AX = B")
print (a* ans)

[[ 3  6 -5]
 [ 1 -3  2]
 [ 5 -1  4]]
[[12]
 [-2]
 [10]]
[[1.75]
 [1.75]
 [0.75]]
****** Verifying Answer as AX = B
[[12.]
 [-2.]
 [10.]]


### using nump.array

In [24]:
a = np.array([
    [3, 6, -5],
    [1, -3, 2],
    [5, -1, 4]
])

b= np.array([
    [12],
    [-2],
    [10]
])

In [25]:
ans = np.linalg.inv(a).dot(b)
print(ans)

[[1.75]
 [1.75]
 [0.75]]


In [1]:
import numpy as np 
arr= np.arange(100000)
my_list = list(range(100000))
%time for _ in range(10) : arr2= arr * 2

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 24.8 ms


In [2]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 76 ms, sys: 8 ms, total: 84 ms
Wall time: 82.9 ms
