In [1]:
import numpy as np 
arr= np.arange(100000)
my_list = list(range(100000))
%time for _ in range(10) : arr2= arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.97 ms
CPU times: user 48 ms, sys: 8 ms, total: 56 ms
Wall time: 56.4 ms


In [4]:
data= np.random.rand(2,3)
data = data* 10
data = data + data


In [5]:
print(data)

[[10.56313331  8.41130927 15.99308147]
 [ 3.83305476  2.11716216 12.70067044]]


In [7]:
data.shape

(2, 3)

In [12]:
# CREATING nDarray

data = [6,7,8,9]
print(type(data))
data = np.array(data)

<class 'list'>


In [10]:
print(data.shape, type(data))

(4,) <class 'numpy.ndarray'>


In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
new_arr = np.array(data2)

In [14]:
new_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
new_arr.shape, type(new_arr)

((2, 4), numpy.ndarray)

In [24]:
# Basic indexing and Slicing
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
print(arr[5])
print(arr[4:9])

5
[4 5 6 7 8]


In [26]:
arr_slice = arr[4:9]
arr_slice

array([4, 5, 6, 7, 8])

In [27]:
arr_slice[1]= 1233
arr

array([   0,    1,    2,    3,    4, 1233,    6,    7,    8,    9])

In [28]:
arr_slice[4] =0
arr

array([   0,    1,    2,    3,    4, 1233,    6,    7,    0,    9])