## Learning Numpy
#### scientific programming include arrays, matrices, interation, differential equations, statistics etc

In [2]:
import numpy as np
print(np.version.full_version)

1.14.3


#### For N-dimentional arrays

In [17]:
# Matrix in numpy will only be two dimentional
# Many ways to create a numpy array
aList = [1,2,3]
print("python list",aList)
arr=np.array(aList)
print("Numpy array",arr)
arr= np.zeros(5)
print("*************")
print(arr)
arr=np.arange(100)
print(arr)
arr=np.arange(10,100)
print(arr)

python list [1, 2, 3]
Numpy array [1 2 3]
*************
[0. 0. 0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [19]:
image=np.zeros((5,5))
print(image, np.ndim(image))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 2


In [4]:
arr= np.zeros(2, dtype= int)
print(arr)
arr = np.zeros(2, dtype=np.float32)
print(arr)

[0 0]
[0. 0.]


In [29]:
# reshaping array in numpy
# Suppose we have 25 element array

arr= np.arange(125)
print(arr[124])
print(arr, np.ndim(arr))
print("************")

arr3d = np.reshape(arr,(5,25))
print("5 rows and 25 columns")
print(arr3d, np.ndim(arr3d))

arr3d = np.reshape(arr,(25,5))
print("25 rows and 5 columns")
print(arr3d, np.ndim(arr3d))

124
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124] 1
************
5 rows and 25 columns
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19  20  21  22  23  24]
 [ 25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
   43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
   68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
   93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 1

In [35]:
arr3d= np.zeros((5,5,5))
arr1d= np.ravel(arr4d)
print(arr1d.shape, np.ndim(arr3d))

(125,) 3


In [54]:
# working on Image
img1 = np.zeros((6,6))+ 3
img1[1:-1, 1:-1] = 6
img1[2:-2, 2:-2] = 9
print(img1)

[[3. 3. 3. 3. 3. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [55]:
index1 = img1 > 2
index2 = img1 < 6
compound_index = index1 & index2
# compound_index = (img1 > 3) & (img1 < 7)
img2 = np.copy(img1)
img2[compound_index] = 0
print(img2)

[[0. 0. 0. 0. 0. 0.]
 [0. 6. 6. 6. 6. 0.]
 [0. 6. 9. 9. 6. 0.]
 [0. 6. 9. 9. 6. 0.]
 [0. 6. 6. 6. 6. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [56]:
index3 = img1 == 9
index4 = (index1 & index2) | index3
img3 = np.copy(img1)
img3[index4] = 0


In [57]:
print(img3)

[[0. 0. 0. 0. 0. 0.]
 [0. 6. 6. 6. 6. 0.]
 [0. 6. 0. 0. 6. 0.]
 [0. 6. 0. 0. 6. 0.]
 [0. 6. 6. 6. 6. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [58]:
img1 = np.zeros((6,6)) + 3
img1[1:-1, 1:-1]=6
img1[2:-2 , 2:-2] = 9
print(img1)
index1 = img1 > 3 
index2= img1 < 7
compound_index= index1 & index2
img2 = np.copy(img1)
img2[compound_index] = 0
print(img2)

[[3. 3. 3. 3. 3. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 3. 3. 3. 3. 3.]]
[[3. 3. 3. 3. 3. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 9. 9. 0. 3.]
 [3. 0. 9. 9. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [59]:
img3= np.copy(img2)
compound_index= (img2>6) & (img2<10)
img3[compound_index] =0
print(img3)

[[3. 3. 3. 3. 3. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 3. 3. 3. 3. 3.]]


### Dealing With Data using Numpy and Pandas

In [83]:

import pandas as pd
import numpy as np

data = pd.read_csv('https://raw.githubusercontent.com/realpython/python-data-cleaning/master/Datasets/BL-Flickr-Images-Book.csv')
print(type(data))
data.head()

<class 'pandas.core.frame.DataFrame'>


Identifier             Edition Statement      Place of Publication  \
0         206                           NaN                    London   
1         216                           NaN  London; Virtue & Yorston   
2         218                           NaN                    London   
3         472                           NaN                    London   
4         480  A new edition, revised, etc.                    London   

  Date of Publication              Publisher  \
0         1879 [1878]       S. Tinsley & Co.   
1                1868           Virtue & Co.   
2                1869  Bradbury, Evans & Co.   
3                1851          James Darling   
4                1857   Wertheim & Macintosh   

                                               Title     Author  \
0                  Walter Forbes. [A novel.] By A. A      A. A.   
1  All for Greed. [A novel. The dedication signed...  A., A. A.   
2  Love the Avenger. By the author of “All for Gr...  A., A. A.   
3  Welsh Sketches, chiefly ecclesiastical, to the...  A., E. S.   
4  [The World in which I live, and my place in it...  A., E. S.   

                                   Contributors  Corporate Author  \
0                               FORBES, Walter.               NaN   
1  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN   
2  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN   
3                   Appleyard, Ernest Silvanus.               NaN   
4                           BROOME, John Henry.               NaN   

   Corporate Contributors Former owner  Engraver Issuance type  \
0                     NaN          NaN       NaN   monographic   
1                     NaN          NaN       NaN   monographic   
2                     NaN          NaN       NaN   monographic   
3                     NaN          NaN       NaN   monographic   
4                     NaN          NaN       NaN   monographic   

                                          Flickr URL  \
0  http://www.flickr.com/photos/britishlibrary/ta...   
1  http://www.flickr.com/photos/britishlibrary/ta...   
2  http://www.flickr.com/photos/britishlibrary/ta...   
3  http://www.flickr.com/photos/britishlibrary/ta...   
4  http://www.flickr.com/photos/britishlibrary/ta...   

                            Shelfmarks  
0    British Library HMNTS 12641.b.30.  
1    British Library HMNTS 12626.cc.2.  
2    British Library HMNTS 12625.dd.1.  
3  British Library HMNTS 10369.bbb.15.  
4     British Library HMNTS 9007.d.28.

In [84]:
to_drop = ['Edition Statement',
'Corporate Author',
'Corporate Contributors',
'Former owner',
'Engraver',
'Contributors',
'Issuance type',
'Shelfmarks']
data.drop(to_drop, inplace=True, axis=1)

In [85]:
data.head()

Identifier      Place of Publication Date of Publication  \
0         206                    London         1879 [1878]   
1         216  London; Virtue & Yorston                1868   
2         218                    London                1869   
3         472                    London                1851   
4         480                    London                1857   

               Publisher                                              Title  \
0       S. Tinsley & Co.                  Walter Forbes. [A novel.] By A. A   
1           Virtue & Co.  All for Greed. [A novel. The dedication signed...   
2  Bradbury, Evans & Co.  Love the Avenger. By the author of “All for Gr...   
3          James Darling  Welsh Sketches, chiefly ecclesiastical, to the...   
4   Wertheim & Macintosh  [The World in which I live, and my place in it...   

      Author                                         Flickr URL  
0      A. A.  http://www.flickr.com/photos/britishlibrary/ta...  
1  A., A. A.  http://www.flickr.com/photos/britishlibrary/ta...  
2  A., A. A.  http://www.flickr.com/photos/britishlibrary/ta...  
3  A., E. S.  http://www.flickr.com/photos/britishlibrary/ta...  
4  A., E. S.  http://www.flickr.com/photos/britishlibrary/ta...

In [86]:
data['Identifier'].is_unique

True

In [87]:
data= data.set_index('Identifier')
data.head()

Place of Publication Date of Publication  \
Identifier                                                 
206                           London         1879 [1878]   
216         London; Virtue & Yorston                1868   
218                           London                1869   
472                           London                1851   
480                           London                1857   

                        Publisher  \
Identifier                          
206              S. Tinsley & Co.   
216                  Virtue & Co.   
218         Bradbury, Evans & Co.   
472                 James Darling   
480          Wertheim & Macintosh   

                                                        Title     Author  \
Identifier                                                                 
206                         Walter Forbes. [A novel.] By A. A      A. A.   
216         All for Greed. [A novel. The dedication signed...  A., A. A.   
218         Love the Avenger. By the author of “All for Gr...  A., A. A.   
472         Welsh Sketches, chiefly ecclesiastical, to the...  A., E. S.   
480         [The World in which I live, and my place in it...  A., E. S.   

                                                   Flickr URL  
Identifier                                                     
206         http://www.flickr.com/photos/britishlibrary/ta...  
216         http://www.flickr.com/photos/britishlibrary/ta...  
218         http://www.flickr.com/photos/britishlibrary/ta...  
472         http://www.flickr.com/photos/britishlibrary/ta...  
480         http://www.flickr.com/photos/britishlibrary/ta...

In [89]:
data.loc[206]

Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [91]:
data.loc[1905:, 'Date of Publication'].head(10)

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object