## Learning Numpy
#### scientific programming include arrays, matrices, interation, differential equations, statistics etc

In [1]:
import numpy as np
print(np.version.full_version)

1.14.5


#### For N-dimentional arrays

In [23]:
# Matrix in numpy will only be two dimentional
# Many ways to create a numpy array
aList = [1,2,3]
arr=np.array(aList)
print(arr)
arr= np.zeros(5)
print(arr)
arr=np.arange(100)
print(arr)
arr=np.arange(10,100)
print(arr)

[1 2 3]
[0. 0. 0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [3]:
image=np.zeros((5,5))
print(image)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
arr= np.zeros(2, dtype= int)
print(arr)
arr = np.zeros(2, dtype=np.float32)
print(arr)

[0 0]
[0. 0.]


In [5]:
# reshaping array in numpy
# Suppose we have 25 element array

arr= np.arange(125)
arr3d = np.reshape(arr,(5,5,5))
print(arr3d)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]


In [6]:
arr4d= np.zeros((5,5,5))
arr1d= np.ravel(arr4d)
print(arr1d.shape)

(125,)


In [46]:

# working on Image

img1 = np.zeros((6,6))+ 3
img1[1:-1, 1:-1] = 6
img1[2:-2, 2:-2] = 9
print(img1)

[[3. 3. 3. 3. 3. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [41]:
# index1 = img1 > 2
# index2 = img1 < 6
# compound_index = index1 & index2
compound_index = (img1 > 3) & (img1 < 7)
img2 = np.copy(img1)
img2[compound_index] = 0
print(img2)

[[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 9. 9. 9. 9. 9. 9. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 9. 9. 9. 9. 9. 9. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 9. 9. 9. 9. 9. 9. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 9. 9. 9. 9. 9. 9. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 9. 9. 9. 9. 9. 9. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 9. 9. 9. 9. 9. 9. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3. 3. 3.]
 [3. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 3.

In [16]:
index3 = img1 == 9
index4 = (index1 & index2) | index3
img3 = np.copy(img1)
img3[index4] = 0


In [17]:
print(img3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0. 0. 0. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0.

In [66]:
img1 = np.zeros((6,6)) + 3
img1[1:-1, 1:-1]=6
img1[2:-2 , 2:-2] = 9
print(img1)
index1 = img1 > 3 
index2= img1 < 7
compound_index= index1 & index2
img2 = np.copy(img1)
img2[compound_index] = 0
print(img2)

[[3. 3. 3. 3. 3. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 9. 9. 6. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 3. 3. 3. 3. 3.]]
[[3. 3. 3. 3. 3. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 0. 9. 9. 0. 3.]
 [3. 0. 9. 9. 0. 3.]
 [3. 0. 0. 0. 0. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [65]:
img3= np.copy(img2)
compound_index= (img2>6) & (img2<10)
img3[compound_index] =0
print(img3)

[[3. 3. 3. 3. 3. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 6. 0. 0. 6. 3.]
 [3. 6. 0. 0. 6. 3.]
 [3. 6. 6. 6. 6. 3.]
 [3. 3. 3. 3. 3. 3.]]
