In [4]:
import numpy as np
from sklearn import datasets

boston_data = datasets.load_boston()


print(boston_data.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [5]:
housing = datasets.fetch_california_housing()

In [6]:
print(housing.DESCR)

California housing dataset.

The original database is available from StatLib

    http://lib.stat.cmu.edu/datasets/

The data contains 20,640 observations on 9 variables.

This dataset contains the average house value as target variable
and the following input variables (features): average income,
housing average age, average rooms, average bedrooms, population,
average occupation, latitude, and longitude in that order.

References
----------

Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
Statistics and Probability Letters, 33 (1997) 291-297.




In [8]:
x, y = boston_data.data , housing.data
datasets.get_data_home()

'/home/mkazim/scikit_learn_data'

In [11]:
regression_data= datasets.make_regression()

In [22]:
import numpy as np
from sklearn import datasets, preprocessing
iris = datasets.load_iris()
x = iris.data
y= iris.target
d = np.column_stack((x,y))
text_encoder = preprocessing.OneHotEncoder()
text_encoder.fit_transform(d[: , -1:]).toarray()[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [23]:
text_encoder.transform((np.ones((3,1)))).toarray()

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [29]:
from sklearn.feature_extraction import DictVectorizer
dv= DictVectorizer()
my_dict = [{'species' : iris.target_names[i]} for i in y]
dv.fit_transform(my_dict).toarray()[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])